source('~/workspace/car-plots/carplots-analysis/src/main/R/carplotsScraperService.R')
.jinit()
carplotsService <- new(serviceClassName)
carplots.makeModels <- getMakeModels(carplotsService)
carplots.locations <- getSearchLocations(carplotsService)
carplots.scraperRuns <- getScraperRuns(carplotsService)
